config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin, :path => ComfyBlog.config.admin_route_prefix do
    namespace :blog do
      resources :posts, :except => [:show] do
        unless ComfyBlog.disqus_enabled?
          resources :comments, :only => [:index]
        end
      end
      unless ComfyBlog.disqus_enabled?
        resources :comments, :only => [:index, :destroy] do
          put :publish, :on => :member
        end
      end
      resources :tags, :except => [:show]
    end
  end unless ComfyBlog.config.admin_route_prefix.blank?
  
  scope ComfyBlog.config.public_route_prefix, :module => :blog do
    get '/'                   => 'posts#index', :as => :blog_posts
    get 'tag/:tag'            => 'posts#index', :as => :tagged_blog_posts
    get 'category/:category'  => 'posts#index', :as => :categorized_blog_posts
    
    with_options :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ } do |o|
      o.get ':year'               => 'posts#index', :as => :year_blog_posts
      o.get ':year/:month'        => 'posts#index', :as => :month_blog_posts
      o.get ':year/:month/:slug'  => 'posts#show',  :as => :dated_blog_post
    end
    
    unless ComfyBlog.disqus_enabled?
      post ':post_id/comments' => 'comments#create', :as => :blog_post_comments
    end
    
    get ':id' => 'posts#show', :as => :blog_post
  end
  
end

app/models/blog/comment.rb
class Blog::Comment < ActiveRecord::Base
  
  self.table_name = :blog_comments
  
  attr_accessible :author,
                  :email,
                  :content
  
  # -- Relationships --------------------------------------------------------
  belongs_to :post
  
  # -- Callbacks ------------------------------------------------------------
  before_create :set_publish
    
  # -- Validations ----------------------------------------------------------
  validates :post_id, :content, :author, :email, 
    :presence => true
  validates :email,
    :format => { :with => /^([\w.%-+]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
    
  # -- Scopes ---------------------------------------------------------------
  scope :published, where(:is_published => true)
  
protected
  
  def set_publish
    self.is_published = ComfyBlog.config.auto_publish_comments
    return
  end
  
end

app/models/blog/post.rb
class Blog::Post < ActiveRecord::Base
  
  self.table_name = :blog_posts

  # -- Attributes -----------------------------------------------------------
  attr_accessor :tag_names,
                :category_ids
  
  # -- Relationships --------------------------------------------------------
  has_many :comments, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings
  
  # -- Validations ----------------------------------------------------------
  validates :title, :slug, :year, :month, :content,
    :presence   => true
  validates :slug,
    :uniqueness => { :scope => [:year, :month] }
  
  # -- Scopes ---------------------------------------------------------------
  default_scope order('published_at DESC')
  
  scope :published, where(:is_published => true)
  scope :for_year, lambda { |year| 
    where(:year => year) 
  }
  scope :for_month, lambda { |month|
    where(:month => month)
  }
  scope :tagged_with, lambda { |tag|
    joins(:tags).where('blog_tags.name' => tag, 'blog_tags.is_category' => false)
  }
  scope :categorized_as, lambda { |tag|
    joins(:tags).where('blog_tags.name' => tag, 'blog_tags.is_category' => true)
  }
  
  # -- Callbacks ------------------------------------------------------------
  before_validation :set_slug,
                    :set_published_at,
                    :set_date
  after_save        :sync_tags,
                    :sync_categories
  
  # -- Instance Methods -----------------------------------------------------
  def tag_names(reload = false)
    @tag_names = nil if reload
    @tag_names ||= self.tags.tags.collect(&:name).join(', ')
  end
  
  def category_ids
    @category_ids ||= self.tags.categories.inject({}){|h, c| h[c.id.to_s] = '1'; h}
  end
  
protected
  
  def set_slug
    self.slug ||= self.title.to_s.slugify
  end
  
  def set_date
    self.year   = self.published_at.year
    self.month  = self.published_at.month
  end
  
  def set_published_at
    self.published_at ||= Time.zone.now
  end
  
  def sync_tags
    return unless tag_names
    self.taggings.for_tags.destroy_all
    self.tag_names.split(',').map{ |t| t.strip }.uniq.each do |tag_name|
      self.tags << Blog::Tag.find_or_create_by_name(tag_name) rescue nil
    end
  end
  
  def sync_categories
    self.category_ids.each do |category_id, flag|
      case flag.to_i
      when 1
        if category = Blog::Tag.categories.find_by_id(category_id)
          category.taggings.create(:post => self) rescue nil
        end
      when 0
        self.taggings.for_categories.where(:tag_id => category_id).destroy_all
      end
    end
  end
  
end

app/models/blog/tag.rb
class Blog::Tag < ActiveRecord::Base

  self.table_name = :blog_tags

  # -- Relationships --------------------------------------------------------
  has_many :taggings, :dependent => :destroy
  has_many :posts, :through => :taggings
    
  # -- Validations ----------------------------------------------------------
  validates_uniqueness_of :name, :case_sensitive => false
  
  # -- Callbacks ------------------------------------------------------------
  before_validation :strip_name
  
  # -- Scopes ---------------------------------------------------------------
  scope :categories,  where(:is_category => true)
  scope :tags,        where(:is_category => false)
  
protected
  
  def strip_name
    self.name = self.name.strip if self.name
  end
  
end

app/models/blog/tagging.rb
class Blog::Tagging < ActiveRecord::Base
  
  self.table_name = :blog_taggings
  
  # -- Relationships --------------------------------------------------------
  belongs_to :post
  belongs_to :tag, :counter_cache => true
  
  # -- Callbacks ------------------------------------------------------------
  after_destroy :destroy_tag
  
  # -- Scopes ---------------------------------------------------------------
  scope :for_tags,        includes(:tag).where('blog_tags.is_category' => false)
  scope :for_categories,  includes(:tag).where('blog_tags.is_category' => true)
  
protected
  
  def destroy_tag
    self.tag.destroy if !self.tag.is_category? && self.tag.taggings.count == 0
  end
  
end

app/controllers/admin/blog/base_controller.rb
class Admin::Blog::BaseController < ComfyBlog.config.admin_controller.to_s.constantize
  # ...
end

app/controllers/admin/blog/comments_controller.rb
class Admin::Blog::CommentsController < Admin::Blog::BaseController
  
  before_filter :load_post,     :only => [:index]
  before_filter :load_comment,  :only => [:destroy, :publish]
  
  def index
    @comments = @post ? @post.comments : Blog::Comment.all
  end
  
  def destroy
    @comment.destroy
  end
  
  def publish
    @comment.update_attribute(:is_published, true)
  end
  
protected
  
  def load_post
    return unless params[:post_id]
    @post = Blog::Post.find(params[:post_id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Blog Post not found'
    redirect_to :action => :index
  end
  
  def load_comment
    @comment = Blog::Comment.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    # ... do nothing
  end
  
end

app/controllers/admin/blog/posts_controller.rb
class Admin::Blog::PostsController < Admin::Blog::BaseController
  
  before_filter :build_post, :only => [:new, :create]
  before_filter :load_post,  :only => [:edit, :update, :destroy]
  
  def index
    @posts = if defined? WillPaginate
      Blog::Post.paginate :page => params[:page]
    elsif defined? Kaminari
      Blog::Post.page params[:page]
    else
      Blog::Post.all
    end
  end
  
  def new
    render
  end
  
  def create
    @post.save!
    flash[:notice] = 'Blog Post created'
    redirect_to :action => :edit, :id => @post
    
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to create Blog Post'
    render :action => :new
  end
  
  def edit
    render
  end
  
  def update
    @post.update_attributes!(params[:post])
    flash[:notice] = 'Blog Post updated'
    redirect_to :action => :edit, :id => @post
    
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to update Blog Post'
    render :action => :edit
  end
  
  def destroy
    @post.destroy
    flash[:notice] = 'Blog Post removed'
    redirect_to :action => :index
  end
  
protected
  
  def load_post
    @post = Blog::Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Blog Post not found'
    redirect_to :action => :index
  end
  
  def build_post
    @post = Blog::Post.new(params[:post])
  end
  
end

app/controllers/admin/blog/tags_controller.rb
class Admin::Blog::TagsController < Admin::Blog::BaseController
  
  before_filter :build_tag, :only => [:new, :create]
  before_filter :load_tag,  :only => [:edit, :update, :destroy]

  def index
    @tags = Blog::Tag.order('is_category DESC', :name)
  end
  
  def edit
    render
  end
  
  def new
    render
  end
  
  def update
    @tag.update_attributes!(params[:tag])
    flash[:notice] = 'Blog Tag updated'
    redirect_to :action => :index
    
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to update Blog Tag'
    render :action => :edit
  end
  
  def create
    @tag.save!
    flash[:notice] = 'Blog Tag created'
    redirect_to :action => :index
    
  rescue ActiveRecord::RecordInvalid
    flash.now[:error] = 'Failed to create Blog Tag'
    render :action => :new
  end
  
  def destroy
    @tag.destroy
    flash[:notice] = 'Blog Tag removed'
    redirect_to :action => :index
  end

protected
  
  def build_tag
    @tag = Blog::Tag.new(params[:tag])
  end
  
  def load_tag
    @tag = Blog::Tag.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Blog Tag not found'
    redirect_to :action => :index  
  end
end

app/controllers/blog/comments_controller.rb
class Blog::CommentsController < ApplicationController
  
  def create
    @post = Blog::Post.published.find(params[:post_id])
    @comment = @post.comments.new(params[:comment])
    @comment.save!
    
    respond_to do |f|
      f.html do 
        flash[:notice] = 'Comment created'
        redirect_to dated_blog_post_path(@post.year, @post.month, @post.slug)
      end
      f.js
    end
    
  rescue ActiveRecord::RecordNotFound
    respond_to do |f|
      f.html do
        flash[:error] = 'Blog Post not found'
        redirect_to blog_posts_path
      end
      f.js do
        render :nothing => true, :status => 404
      end
    end
    
  rescue ActiveRecord::RecordInvalid
    respond_to do |f|
      f.html do
        render 'blog/posts/show'
      end
      f.js
    end
  end
end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController
  
  layout ComfyBlog.config.public_layout
  
  def index
    scope = if params[:tag]
      Blog::Post.published.tagged_with(params[:tag])
    elsif params[:category]
      Blog::Post.published.categorized_as(params[:category])
    elsif params[:year]
      scope = Blog::Post.published.for_year(params[:year])
      params[:month] ? scope.for_month(params[:month]) : scope
    else
      Blog::Post.published
    end
    
    respond_to do |f|
      f.html do
        @posts = if defined? WillPaginate
          scope.paginate :per_page => ComfyBlog.config.posts_per_page, :page => params[:page]
        elsif defined? Kaminari
          scope.page(params[:page]).per(ComfyBlog.config.posts_per_page)
        else
          scope
        end
      end
      f.rss do
        @posts = scope.limit(ComfyBlog.config.posts_per_page)
      end
    end
  end
  
  def show
    @post = if params[:slug] && params[:year] && params[:month]
      Blog::Post.published.find_by_year_and_month_and_slug!(params[:year], params[:month], params[:slug])
    else
      Blog::Post.published.find(params[:id])
    end
  rescue ActiveRecord::RecordNotFound
    if defined? ComfortableMexicanSofa
      render :cms_page => '/404', :status => 404
    else
      render :text => 'Post not found', :status => 404
    end
  end
end

app/helpers/blog/application_helper.rb
module Blog::ApplicationHelper
  
  def comfy_blog_form_for(record_or_name_or_array, *args, &proc)
    options = args.extract_options!
    form_for(
      record_or_name_or_array,
      *(args << options.merge(:builder => ComfyBlog.config.form_builder.to_s.constantize)),
      &proc
    )
  end
  
  # URL helpers for blog_post_(path/url)
  %w(path url).each do |type|
    define_method "blog_post_#{type}" do |post|
      send("dated_blog_post_#{type}", post.year, ("%02d" % post.month), post.slug)
    end
  end
  
  def blah
    'blah'
  end
  
end

app/views/admin/blog/posts/_form.html.erb
<%= form.text_field :title, :id => (@post.new_record?? 'slugify' : nil) %>
<%= form.text_field :slug, :id => 'slug' %>
<%= form.text_field :author %>
<% if Blog::Tag.categories.present? %>
  <%= form.simple_field 'Categories' do %>
    <% Blog::Tag.categories.each do |category| %>
      <%= hidden_field_tag "post[category_ids][#{category.id}]", 0, :id => nil %>
      <label>
        <%= check_box_tag "post[category_ids][#{category.id}]", 1, @post.category_ids[category.id.to_s].to_i == 1, :id => nil %>
        <%= category.name %>
      </label>
    <% end %>
  <% end %>
<% end %>
<%= form.text_field :tag_names, :label => link_to('Tags', admin_blog_tags_path) %>
<%= form.text_area :excerpt, :class => 'short' %>
<%= form.text_area :content, :class => 'rich_text' %>
<%= form.text_field :published_at, :class => 'datetime' %>

<% if defined?(ComfortableMexicanSofa) %>
  <% content_for :right_column do %>
    <%= render :partial => 'cms_admin/files/index' %>
  <% end %>
  
  <%= cms_hook :blog_post, :locals => { :form => form } %>
  
  <%= form.simple_field nil, nil, :class => 'submit_element' do %>
    <%= form.check_box :is_published, :disable_builder => true %>
    <%= form.label_for :is_published %>
    <%= form.submit @post.new_record?? 'Create post' : 'Update post', :disable_builder => true %>
  <% end %>
  
<% else %>
  <%= form.check_box :is_published %>
  <%= form.submit @post.new_record?? 'Create post' : 'Update post' %>
<% end %>

app/views/admin/blog/posts/_post.html.erb
<li>
  <div class='item'>
    <div class='icon <%= post.is_published?? 'published' : 'draft' %>'></div>
    <div class='action_links'>
      <% unless ComfyBlog.disqus_enabled? %>
        <%= link_to pluralize(post.comments.count, 'comment'), admin_blog_post_comments_path(post) %>
      <% end %>
      <%= link_to 'Edit', edit_admin_blog_post_path(post) %>
      <%= link_to 'Delete', admin_blog_post_path(post), :method => :delete, :confirm => 'Are you sure?' %>
    </div>
    <div class='label'>
      <%= link_to post.title.titleize, edit_admin_blog_post_path(post) %>
      <div class='sublabel'>
        Published <%= time_ago_in_words(post.created_at) %> ago
        
        <% if post.author.present? %>
          by <strong><%= post.author %></strong>
        <% end %>
        
        <% if post.tags.count > 0 %>
          Tagged with:
          <% post.tags.each do |tag| %>
            <span class="tag"><%= tag.name %></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</li>

app/views/admin/blog/posts/edit.html.erb
<h1>Editing <%= @post.title.titleize %></h1>

<%= comfy_blog_form_for @post, :as => :post, :url => {:action => :update} do |form| %>
  <%= render :partial => form %>
<% end %>

app/views/admin/blog/posts/index.html.erb
<%= link_to 'Add new blog post', new_admin_blog_post_path, :class => 'big button' %>

<h1>Blog Posts</h1>

<ul class='list posts'>
  <% @posts.each do |post| %>
    <%= render :partial => 'post', :object => post %>
  <% end %>
</ul>

<% if defined?(WillPaginate) %>
  <%= will_paginate @posts %>
<% elsif defined?(Kaminari)%>
  <%= paginate @posts %>
<% end %>

app/views/admin/blog/posts/new.html.erb
<h1>New Blog Post</h1>

<%= comfy_blog_form_for @post, :as => :post, :url => {:action => :create} do |form| %>
  <%= render :partial => form %>
<% end %>